server:
  port: 8080
spring:
  application:
    name: elasticSearchDemo
  datasource:
    url: jdbc:mysql://localhost:3306/tic?useSSL=false&serverTimezone=UTC
    username: root
    password: 1686407441
    driver-class-name: com.mysql.cj.jdbc.Driver
  elasticsearch:
    uris:
      - http://127.0.0.1:9200
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  kafka:
    bootstrap-servers:
      - localhost:9092
    consumer:
      group-id:
      auto-offset-reset: earliest
powerjob:
  worker:
    enabled: true
    allow-lazy-connect-server: false
    app-name: elasticSearchDemo
    port: 27777
    server-address: 127.0.0.1:7700
    protocol: "HTTP"
    store-strategy: DISK
    max-result-length: 4096
    max-appended-wf-context-length: 4096
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.elasticSearchDemo.entity
  configuration:
    map-underscore-to-camel-case: true
minio:
  access-key: minioadmin
  secret-key: minioadmin
  url: http://127.0.0.1:9000
  bucket-name: test